name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Mau
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: pnpm@9.12.1+sha512.e5a7e52a4183a02d5931057f7a0dbff9d5e9ce3161e33fa68ae392125b79282a8a8a470a51dfc8a0ed86221442eb2fb57019b0990ed24fab519bf0e1bc5ccfc4
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Environment (PR)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          echo "GIT_HASH=${{ github.event.pull_request.head.sha }}" >>${GITHUB_ENV}
      - name: Setup Environment (Push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          echo "GIT_HASH=${GITHUB_SHA}" >> ${GITHUB_ENV}
      - name: Push and deploy
        run: npx @nestjs/mau deploy --wait-for-service-stability
        env:
          MAU_KEY: ${{ secrets.MAU_KEY }}
          MAU_SECRET: ${{ secrets.MAU_SECRET }}
